CREATE DATABASE CompanyDB
CREATE SCHEMA SALES

CREATE SEQUENCE I
AS INT
START WITH 1
INCREMENT BY 1

CREATE TABLE SALES.EMPLOYEES(
EMP_ID INT DEFAULT (NEXT VALUE FOR I),
FIRST_NAME VARCHAR(1000),
LAST_NAME VARCHAR(1000),
SALARY DECIMAL
)

ALTER TABLE SALES.EMPLOYEES
ADD HIRE_DATE DATE 

SELECT *
FROM SALES.EMPLOYEES

SELECT FIRST_NAME , LAST_NAME
FROM SALES.EMPLOYEES

SELECT FIRST_NAME+' '+LAST_NAME FULL_NAME
FROM SALES.EMPLOYEES

SELECT AVG(SALARY) AS AVE_SALARY
FROM SALES.EMPLOYEES

SELECT *
FROM SALES.EMPLOYEES
WHERE SALARY > 50000 

SELECT *
FROM SALES.EMPLOYEES
WHERE HIRE_DATE LIKE '2020%'

SELECT *
FROM SALES.EMPLOYEES
WHERE LAST_NAME LIKE 'S%'

SELECT TOP 10 *
FROM SALES.EMPLOYEES
ORDER BY SALARY DESC

SELECT *
FROM SALES.EMPLOYEES
WHERE SALARY BETWEEN 40000 AND 60000

SELECT FIRST_NAME+' '+LAST_NAME AS FULL_NAME
FROM SALES.EMPLOYEES
WHERE FIRST_NAME LIKE 'MAN' OR LAST_NAME LIKE 'MAN'

SELECT HIRE_DATE
FROM SALES.EMPLOYEES
WHERE HIRE_DATE IS NULL

SELECT *
FROM SALES.EMPLOYEES
WHERE SALARY LIKE 40000 OR SALARY LIKE 45000 OR SALARY LIKE 50000

SELECT * 
FROM SALES.EMPLOYEES
WHERE SALARY =  40000 OR SALARY = 45000 OR SALARY = 50000

SELECT * 
FROM SALES.EMPLOYEES
WHERE HIRE_DATE BETWEEN '2020-01-01' AND '2021-01-01'

SELECT *
FROM SALES.EMPLOYEES
ORDER BY SALARY DESC

SELECT TOP 5 *
FROM SALES.EMPLOYEES
ORDER BY LAST_NAME ASC

SELECT *
FROM SALES.EMPLOYEES
WHERE SALARY > 55000 AND HIRE_DATE LIKE '2020%'

SELECT *
FROM SALES.EMPLOYEES
WHERE  FIRST_NAME LIKE 'JOHN' OR FIRST_NAME LIKE 'JANE'

SELECT *
FROM SALES.EMPLOYEES
WHERE SALARY<=55000 AND HIRE_DATE > '2022-01-01'

SELECT *
FROM SALES.EMPLOYEES
WHERE SALARY>(SELECT AVG(SALARY) FROM SALES.EMPLOYEES)  

SELECT *
FROM SALES.EMPLOYEES
ORDER BY SALARY DESC 
OFFSET 2 ROWS
FETCH NEXT 5 ROWS ONLY 

SELECT FIRST_NAME+' '+LAST_NAME EMPLOYEE_NAME , EMP_ID,SALARY,HIRE_DATE
FROM SALES.EMPLOYEES
WHERE HIRE_DATE> '2021-01-01'
ORDER BY EMPLOYEE_NAME 

SELECT *
FROM SALES.EMPLOYEES
WHERE SALARY>50000 AND LAST_NAME NOT LIKE 'A%'

SELECT *
FROM SALES.EMPLOYEES
WHERE SALARY IS NOT NULL

SELECT FIRST_NAME+' '+LAST_NAME EMP_NAME,SALARY,HIRE_DATE
FROM SALES.EMPLOYEES
WHERE FIRST_NAME LIKE '%E%' OR FIRST_NAME LIKE '%L%' AND SALARY > 45000

SELECT TOP 10 *
FROM SALES.EMPLOYEES
ORDER BY SALARY DESC

SELECT *
FROM SALES.EMPLOYEES
WHERE SALARY BETWEEN 40000 AND 60000


SELECT HIRE_DATE
FROM SALES.EMPLOYEES
WHERE HIRE_DATE IS NULL





